environment: development
databases:
  default:
    host: database
    port: 5432
    database: projectdb
    user: dbuser
    password: secret
secret_key: m8d%u$-8ab=gr=z%1n&$u2g5h(%j&s0_hf!w(8x&9(830$q&2#
